#include <bits/stdc++.h>
using namespace std;

int main() {
    int n;
    cin >> n;

    vector<int> arr(n);

    for (int i = 0; i < n; i++)
        cin >> arr[i];

    sort(arr.begin(), arr.end());

    int mini = INT_MAX;

    for (int i = 1; i < n; i++)
        mini = min(mini, arr[i] - arr[i - 1]);

    for (int i = 1; i < n; i++) {
        if (arr[i] - arr[i - 1] == mini)
            cout << arr[i - 1] << " " << arr[i] << endl;
    }

    return 0;
}
// dehpolaaaaaaaaaaaaaaaaaaaaaaaaaaa